### ISSUE TITLE
User Story #1: Journal page layout

### ISSUE THREAD

**Issue by ChoiSojung** [mattyplo/FoodDiary#1]
As a user I want to see my meals separated by date

**Comment by mattyplo** [comment]
This issue is partially done.  The journal page will render and display meals from mockData.  The page will eventually need to pull its data from the db.

**Comment by mattyplo** [comment]
The journal page now displays meals by date.  
The next plausible UserStory to lead from the completion of this would be,
As a user I want my meals to be sorted by date so that I can more easily find a particular meal from a moment in time.
