### ISSUE TITLE
User Story #2: Journal page sections layout

### ISSUE THREAD

**Issue by ChoiSojung** [mattyplo/FoodDiary#2]
As a user I want to see my date entries separated into sections for Breakfast, Lunch, Dinner, and Snacks.

**Comment by ChoiSojung** [comment]
Changed title to clarify this issue

**Comment by mattyplo** [comment]
User Story #2 now complete.  Journal entries are separated into dates, then further separated into meal types breakfast, lunch, dinner and snack.
