### ISSUE TITLE
User Story #21: Welcome page and About

### ISSUE THREAD

**Issue by ChoiSojung** [mattyplo/FoodDiary#21]
As a user, I want information on how the app works and welcome text to help me know where I should go next.

**Comment by QuincyPowell** [comment]
Basic completeness level done.
Accomplished: .pug file written that contains page structure
.css file specific to landing page (which does not need nav bar) written.
Information paragraph written
Login form created but not connected
ToDo: Connect form to database and write authentication method(s)
Update .css file for custom font
Update .css file to make "pretty" and color / style consistent with internal pages

**Comment by QuincyPowell** [comment]
Closing user story 21
Database connections are in scope for other user stories
The page is "pretty enough"
