### ISSUE TITLE
User Story #8.1 Discussion FK Constraint behavior needs to be discussed 

### ISSUE THREAD

**Issue by YunFSui** [mattyplo/FoodDiary#22]
e.g. If a food item is associated with a meal, should we prohibit the deletion of the said food item, or grab the error code and warn the user that the deletion will also delete all the entries of that food in all the meals (cascade deletion of FK items in meals foods.)

**Comment by YunFSui** [comment]
I personally think prohibit is a easier way out and safe option for FK constraints.

**Comment by mattyplo** [comment]
I think that we should prohibit a food item from being deleted if it's already associated with a meal.

**Comment by YunFSui** [comment]
Discussed in team meeting 2/19/2019, resolved.
