### ISSUE TITLE
User Story #5: User Information Privacy

### ISSUE THREAD

**Issue by ChoiSojung** [mattyplo/FoodDiary#5]
As a user I want my information (journal page, profile, food db) to stay private and only viewable to me because it is sensitive information.

**Comment by mattyplo** [comment]
User Story #5 is now complete!  express-sessions module was added.  When a user logs in at the login in page a session saves their id and a token is saved in the session allowing access to the site.  Each page, the journal and foods page have a auth function assigned to them that must be passed with the session token in order for access to be acquired.
