### ISSUE TITLE
User Story #6: User Login

### ISSUE THREAD

**Issue by ChoiSojung** [mattyplo/FoodDiary#6]
As a user I want to be able to login to access my user account and personal data.

**Comment by QuincyPowell** [comment]
Checkout branch US6-Powell for login stuff.
Added form handler route for login
Added login failure route that displays a form to try login again
Login success hands off to journal page, but crashes app
Login failure tries to hand off to failure page, and crashes app

**Comment by QuincyPowell** [comment]
Corrected method call to properly redirect to...
...login failure page on login fail
...journal page on login success
Discovered some corner cases that need addressed
1. User supplies no password results in error
2. User does not exist results in error
Additionally Matt observed the login failure page throwing an "unexpected block content" error while rendering the PUG.

**Comment by mattyplo** [comment]
Redirect Issue for a failed login fixed, if a user enters a bad password, they are redirected to the login page.
